name: Continuous deployment
on: 
  push:
    branches: [ master ]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploying changes in master branch to production (vasfe.com.br)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        key: ${{ secrets.SSH_DEPLOYMENT_KEY }}
        passphrase: ${{ secrets.DEPLOY_SSH_PASSPHRASE }}
        script: ~/deployment.sh
